language: python

python:
    - 3.8

env:
    - SECRET_KEY='Test'

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8

before_script:
  - python manage.py migrate

script:
  - python manage.py
  - python -m black . --check
  - python -m flake8 --max-line-length=92
  - python -m coverage run -m --source='.' manage.py test

after_success:
  - coveralls
